// <auto-generated />
namespace Week09.Data.ClassLib.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Initialclubstructure : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initialclubstructure));
        
        string IMigrationMetadata.Id
        {
            get { return "202211160959434_Initial club structure"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
