// <auto-generated />
namespace Rad3012223.MVC.Week5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Week5Databaseinitialised : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Week5Databaseinitialised));
        
        string IMigrationMetadata.Id
        {
            get { return "202210260947394_Week 5 Database initialised"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
