// <auto-generated />
namespace Week10ClassLibrarys00211357.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class StudentWithRegisteredDateAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StudentWithRegisteredDateAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "202211231013247_Student With Registered Date Added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
