// <auto-generated />
namespace Week12MVCHealthApp2223.S00211357.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class MVCInitialMigrationS00211357 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MVCInitialMigrationS00211357));
        
        string IMigrationMetadata.Id
        {
            get { return "202212070941110_MVC Initial Migration S00211357"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
