// <auto-generated />
namespace Week3ClubDomain22.BusinessModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ClubModeladded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ClubModeladded));
        
        string IMigrationMetadata.Id
        {
            get { return "202210050948176_Club Model added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
