// <auto-generated />
namespace Week8ClassLibary2022.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ClubContextCreate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ClubContextCreate));
        
        string IMigrationMetadata.Id
        {
            get { return "202211090931423_Club Context Create"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
